const CLASE_BOOTSTRAP_DISPLAY_NONE = "d-none";

const CLASES_BOOTSTRAP_ALERTA_ERROR = ['invalid-feedback', 'd-block', 'text-center'];
const ID_ALERTA_ERROR = "alertaError";

const CLASES_BOOTSTRAP_DIV_PLATILLO = ['row', 'border-top'];
const CLASES_BOOTSTRAP_DIV_NOMBRE_PLATILLO = ['col-md-4', 'py-3'];
const CLASES_BOOTSTRAP_DIV_PRECIO_PLATILLO = ['col-md-3', 'py-3', 'fw-bold'];
const CLASES_BOOTSTRAP_DIV_CATEGORIA_PLATILLO = ['col-md-3', 'py-3'];
const CLASES_BOOTSTRAP_DIV_AGREGAR_PLATILLO = ['col-md-2', 'py-3'];
const CLASE_BOOTSTRAP_INPUT_CANTIDAD_PLATILLO = "form-control";

const CLASE_BOOTSTRAP_SPAN_RESUMEN_PEDIDO = 'fw-normal';
const CLASES_BOOTSTRAP_H3_ENCABEZADO_RESUMEN_PEDIDO = ['my-4',"text-center"];

const CLASES_BOOTSTRAP_DIV_CONTENEDOR_RESUMEN_PEDIDO = ['col-md-6', 'card', 'py-5', 'px-3', 'shadow'];
const CLASE_BOOTSTRAP_PARRAFO_PEDIDO = 'fw-bold';
const CLASE_BOOTSTRAP_UL_LISTA_PLATILLOS_PEDIDO = "list-group";
const CLASE_BOOTSTRAP_LI_PLATILLO_PEDIDO = 'list-group-item';
const CLASES_BOOTSTRAP_H4_NOMBRE_PLATILLO_PEDIDO = ['text-center', 'my-4'] 
const CLASES_BOOTSTRAP_BOTON_ELIMINAR_PLATILLO_PEDIDO =['btn', 'btn-danger'];

const ID_FORMULARIO_PROPINAS = "formularioPropinas"
const CLASES_BOOTSTRAP_DIV_FORMULARIO_PROPINAS = ['col-md-6', 'formulario'];
const CLASES_BOOTSTRAP_DIV_CONTENEDOR_FORMULARIO_PROPINAS = ['card', 'py-5', 'px-3', 'shadow'];
const CLASE_BOOTSTRAP_INPUT_RADIO_FORMULARIO_PROPINAS = 'form-check-label';
const CLASE_BOOTSTRAP_LABEL_FORMULARIO_PROPINAS = 'form-check-label';
const CLASE_BOOTSTRAP_DIV_CONTENEDOR_INPUT_FORMULARIO_PROPINAS = 'form-check';

const ID_CONTENEDOR_DESGLOSE = "contenedorDesglose";
const CLASES_BOOTSTRAP_PARRAFO_TOTAL_PLATILLOS_DESGLOSE = ['fs-3', 'fw-bold', 'mt-5']
const CLASES_BOOTSTRAP_PARRAFO_TOTAL_DESGLOSE = ['fs-3', 'fw-bold']

export default{
    CLASE_BOOTSTRAP_DISPLAY_NONE,

    CLASES_BOOTSTRAP_ALERTA_ERROR,
    ID_ALERTA_ERROR,

    CLASES_BOOTSTRAP_DIV_PLATILLO,
    CLASES_BOOTSTRAP_DIV_NOMBRE_PLATILLO,
    CLASES_BOOTSTRAP_DIV_PRECIO_PLATILLO,
    CLASES_BOOTSTRAP_DIV_CATEGORIA_PLATILLO,
    CLASES_BOOTSTRAP_DIV_AGREGAR_PLATILLO,
    CLASE_BOOTSTRAP_INPUT_CANTIDAD_PLATILLO,

    CLASE_BOOTSTRAP_SPAN_RESUMEN_PEDIDO,
    CLASES_BOOTSTRAP_H3_ENCABEZADO_RESUMEN_PEDIDO,

    CLASES_BOOTSTRAP_DIV_CONTENEDOR_RESUMEN_PEDIDO,
    CLASE_BOOTSTRAP_PARRAFO_PEDIDO,
    CLASE_BOOTSTRAP_UL_LISTA_PLATILLOS_PEDIDO,
    CLASE_BOOTSTRAP_LI_PLATILLO_PEDIDO,
    CLASES_BOOTSTRAP_H4_NOMBRE_PLATILLO_PEDIDO,
    CLASES_BOOTSTRAP_BOTON_ELIMINAR_PLATILLO_PEDIDO,

    ID_FORMULARIO_PROPINAS,
    CLASES_BOOTSTRAP_DIV_FORMULARIO_PROPINAS,
    CLASES_BOOTSTRAP_DIV_CONTENEDOR_FORMULARIO_PROPINAS,
    CLASE_BOOTSTRAP_INPUT_RADIO_FORMULARIO_PROPINAS,
    CLASE_BOOTSTRAP_LABEL_FORMULARIO_PROPINAS,
    CLASE_BOOTSTRAP_DIV_CONTENEDOR_INPUT_FORMULARIO_PROPINAS,
    
    ID_CONTENEDOR_DESGLOSE,
    CLASES_BOOTSTRAP_PARRAFO_TOTAL_PLATILLOS_DESGLOSE,
    CLASES_BOOTSTRAP_PARRAFO_TOTAL_DESGLOSE,
}